# Generated by Django 2.1.8 on 2019-08-27 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_registration', '0002_user_is_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_administrator',
            field=models.BooleanField(default=False, verbose_name='administrator status'),
        ),
    ]
